"""baseline_backend_schema

Revision ID: b43c81f94761
Revises: 
Create Date: 2026-04-05 00:07:30.706573

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import backend.core.database


# revision identifiers, used by Alembic.
revision = 'b43c81f94761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('request_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('skill_id', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', backend.core.database.INETType(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metadata', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_tracking_period'), 'cost_tracking', ['period'], unique=False)
    op.create_index(op.f('ix_cost_tracking_user_id'), 'cost_tracking', ['user_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('enabled_for', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_name', 'model_id', name='uq_feature_model')
    )
    op.create_table('model_access_control',
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('allowed_roles', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('max_tokens_per_request', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('model_configurations',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('secret_reference_key', sa.String(length=255), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('request_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('parameters', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'provider', name='uq_model_configuration')
    )
    op.create_index(op.f('ix_model_configurations_model_id'), 'model_configurations', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_configurations_provider'), 'model_configurations', ['provider'], unique=False)
    op.create_table('model_permissions',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('granted_by', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('revoked_by', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_id', name='uq_user_model')
    )
    op.create_index(op.f('ix_model_permissions_user_id'), 'model_permissions', ['user_id'], unique=False)
    op.create_table('registered_models',
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_per_1k_tokens', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('secret_references',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('reference_key', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_key', name='uq_secret_reference_key')
    )
    op.create_table('skill_assignments',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('assigned_by', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('revoked_by', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.create_index(op.f('ix_skill_assignments_user_id'), 'skill_assignments', ['user_id'], unique=False)
    op.create_table('skill_definitions',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('required_models', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('input_schema', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('output_format', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('execution_handler', sa.String(length=500), nullable=False),
    sa.Column('error_handling', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('created_by', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'version', name='uq_skill_definition_version')
    )
    op.create_index(op.f('ix_skill_definitions_skill_id'), 'skill_definitions', ['skill_id'], unique=False)
    op.create_table('skill_states',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'version', name='uq_skill_state_version')
    )
    op.create_index(op.f('ix_skill_states_is_enabled'), 'skill_states', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_skill_states_skill_id'), 'skill_states', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_states_updated_at'), 'skill_states', ['updated_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('max_tokens_per_request', sa.Integer(), nullable=False),
    sa.Column('allowed_models', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('features', backend.core.database.JSONEncoded(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('cost_budget_monthly', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('plan_name')
    )
    op.create_table('token_usage_log',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('request_id', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_log_model_id'), 'token_usage_log', ['model_id'], unique=False)
    op.create_index(op.f('ix_token_usage_log_user_id'), 'token_usage_log', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('assigned_by', backend.core.database.GUID(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_subscription')
    )
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('tokens_limit', sa.Integer(), nullable=False),
    sa.Column('cost_accumulated', sa.Float(), nullable=False),
    sa.Column('last_reset', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='uq_user_period')
    )
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', backend.core.database.GUID(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('platform_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', backend.core.database.JSONEncoded(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_token_usage_log_user_id'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_model_id'), table_name='token_usage_log')
    op.drop_table('token_usage_log')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_skill_states_updated_at'), table_name='skill_states')
    op.drop_index(op.f('ix_skill_states_skill_id'), table_name='skill_states')
    op.drop_index(op.f('ix_skill_states_is_enabled'), table_name='skill_states')
    op.drop_table('skill_states')
    op.drop_index(op.f('ix_skill_definitions_skill_id'), table_name='skill_definitions')
    op.drop_table('skill_definitions')
    op.drop_index(op.f('ix_skill_assignments_user_id'), table_name='skill_assignments')
    op.drop_table('skill_assignments')
    op.drop_table('secret_references')
    op.drop_table('registered_models')
    op.drop_index(op.f('ix_model_permissions_user_id'), table_name='model_permissions')
    op.drop_table('model_permissions')
    op.drop_index(op.f('ix_model_configurations_provider'), table_name='model_configurations')
    op.drop_index(op.f('ix_model_configurations_model_id'), table_name='model_configurations')
    op.drop_table('model_configurations')
    op.drop_table('model_access_control')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_cost_tracking_user_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_period'), table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
